language: python
python:
  - "3.3"
  - "3.4"

# command to install dependencies
install: "pip install -r requirements.txt"

# command to run tests
script: ./citests.sh

after_success: ./cipublish.py

env:
  secure: "Ke/4LtHONUIApHdH3lDBGtHj9ilfca2rxHFFOERNv+gEVEMhm+gxB+015yVdNH4AQjQ+gTmb1MIOOF90YGJU7X5ExyTpGLV5g6tJ7foJaLKGJPusAHpadXp29QtQLlTHcgj0lYBZFdPaKZRA8CpOAiMz98PsTBq8qfWx/rqNFgcSLNxEHBe5MKT4Qv2aQwmrhgrjG4HuCDjtVe/6lBWR4L6bQr6qapH5th+Qo1130pk12JF2s2HvJVJ2kfhqukYYLLkVPelAWDBADWtgfnqmSp7+pphrIYtoo7e1EHG7LQmHl5OCUqMjppE9CiLqX1egrVVEXGE8PhFjMRVJk4Ypy6GGfShB+MzqRh0wLMAKBTBKTv0yJ0LnvJsdbN37DjG9UQ5j+YYpwOs+GcIAQ5Vlw5fpxcgX5+q7o3mpKx9sKCooLsoDIQoBjpPeAP0X6ObsTvMN4/xUEDIZrTx0tE5mgzZK9gHoHwD2zkoBv+HIdAER6IqglH4zc8GHeEa7G82i/r/NALSJsA9GH1WVw3Y63de3Zl8we6l2U5dMYDpjhXZTGqVToaE+kF5HqlYMkbVgsblEOEyIyrQ787nuFpDtPbITNrpU8gMhwD4g6AhgOepeM/mk6zJCat/pu27wCFTrf4P+0g75LfVSJomToJ3Q8CCdBEZ/qUEo03C2U8P2r/E="
